### ISSUE TITLE
AdBlocker blocks module imports

### ISSUE THREAD

**Issue by marcel-gohsen** [fidelthomet/futuring-machines#1]
On Firefox together with "AdBlocker Ultimate" the module imports get blocked. As a result, the front page stays white, and I get warnings in the console (see image).  Disabling the AdBlocker fixes it, but it would be nice if it would work with an enabled AdBlocker. 
![image](https://github.com/fidelthomet/futuring-machines/assets/29226023/0a84df85-9536-4155-be45-2ccdb7da7cea)

**Comment by fidelthomet** [comment]
Hi, that's strange. But I can't reproduce this with the extension freshly installed. Do you have any custom settings/filters?

Is this affecting only the local dev version or also the production build?

**Comment by marcel-gohsen** [comment]
I don't have any custom settings. This just happened to the local dev version. The production build seems to not have the problem.
