### ISSUE TITLE
Local caching of stories

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#10]
We did want to store the stories somehow to avoid losing them.

There is one "problem" with the current solution: if one wants to generate new story with the same template the previous story is loaded. What should be done here in order to start a new story? Open the tool with another tab? (a pragmatic workaround for the upcoming workshops)

Could this be solved in another way after the workshops?

**Comment by fidelthomet** [comment]
updated version has a more sophisticated strategy
- selecting a template always initiates a new story
- started stories can be found under recent stories on the index page

fyi
- this also now uses localstorage, making them generally more persistent
- it would be fairly straightforward to exchange the localstorage backend with something server side
