### ISSUE TITLE
LLM-API calls fail silently

### ISSUE THREAD

**Issue by marcel-gohsen** [fidelthomet/futuring-machines#2]
In case the LLM API is not available or sends a non-200 response, the front-end fails silently. It would be helpful for debugging if there would be an error message in the front-end and not only in the console.

**Comment by jorditost** [comment]
When the LLM API is down the API call still failes silently (see in screenshot the console error and the loading animation on the interface):

<img width="1552" alt="Screenshot 2024-09-05 at 13 01 57" src="https://github.com/user-attachments/assets/a1d9f49c-63e7-4ce4-8a19-8cbd1cc1c1b5">
