### ISSUE TITLE
Insert text at cursor position

### ISSUE THREAD

**Issue by fidelthomet** [fidelthomet/futuring-machines#28]
generated text is currently inserted at the end of existing text

- [ ] check if this behaviour is always desired

**Comment by jorditost** [comment]
We should check if this behaviour is always desired. If yes: the text is now inserted at cursor position but (see screenshot) the full story is still passed to the LLM. The prompt should only include the story text until the cursor position.

See example:

Cursor position is between Row 2 and Row 3.
<img width="806" alt="Screenshot 2024-09-05 at 13 10 33" src="https://github.com/user-attachments/assets/06c68b43-1741-468e-a5fe-ce572514595f">

After "Continue writing":
![Screenshot 2024-09-05 at 12 16 58](https://github.com/user-attachments/assets/646aa5ef-1e26-4c73-a283-922a3d7afe0b)

**Comment by fidelthomet** [comment]
in the prompt template replace `::full::` with `::before::` (see #27)

there was a bug which made the tags only available on selection prompts which was fixed with 08ab960fafb63e2812cb2b25e783cc962606d0e8

08ab960fafb63e2812cb2b25e783cc962606d0e8 also replaces ::full:: with ::before:: in the continue writing prompt
