### ISSUE TITLE
When loading an empty template, the content is not centered to the screen.

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#42]
Centering only happens when the story has some text (or after typing some text).

After loading template:
<img width="1440" alt="Screenshot 2024-09-05 at 13 17 52" src="https://github.com/user-attachments/assets/6e91ed17-bba7-403b-91d5-5b866a2c5713">

After typing:
<img width="1440" alt="Screenshot 2024-09-05 at 13 17 24" src="https://github.com/user-attachments/assets/d9a8cdd6-7ab6-4beb-8a1b-02be1f71d0e7">

**Comment by fidelthomet** [comment]
i mainly added the empty template for testing. is that even something you'd like to have in there?

anyway, this feels very minor to me. but please reopen if you really want this fixed.
