### ISSUE TITLE
Templates: how to select EN and/or DE templates in the tamplates overview?

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#44]
The thingFromTheFuture.js is multilingual (en+de). There are some related issues:

- The Tamplates page only shows the German one by default.
- It should be possible to specify which templates to activate (e.g. only DE, only EN, both).

**Comment by fidelthomet** [comment]
you can change the language in `/settings`.

we can discuss adding a language switch on the index page as well. wouldn't see a case for having the both option then tho

**Comment by jorditost** [comment]
With `/settings` you mean the browser settings, right? 
A language switch would make sense, specially since in the workshops we use computers from the computer pool at the university (or from the city, in Herzberg). User could then easily choose the language it makes more sense to them.
