### ISSUE TITLE
Prompts: german promps are always executed by default (also in English templates)

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#45]
See this example:

![Screenshot 2024-09-06 at 17 30 58](https://github.com/user-attachments/assets/7f51d0a6-6814-4438-8161-d8e76f5e66a9)

**Comment by fidelthomet** [comment]
i can't reproduce this. is this a story that was started / saved before the latest update?

when creating a new story, the currently selected language is saved with the story. this was not the case before, therefore it is likely that opening an old story in a different language to the currently selected one caused this issue

**Comment by jorditost** [comment]
It's happening with a new story and using the futuresOfDesign.js template. See here how the story is started in English and prompts (the generated text then, too) are in German. I've tested in Firefox and Chrome and my default language in both Browsers (and OS) is English.

![Screenshot 2024-09-10 at 18 27 00](https://github.com/user-attachments/assets/7a2f66c6-8d1e-4825-be7f-bebdb5bf4d14)

**Comment by fidelthomet** [comment]
Unfortunately, I still can't reproduce this following the steps you described. Can you export the story json and check if the lang property is set to `en`

**Comment by jorditost** [comment]
the lang property is set to `de`:

[e6decc58.json](https://github.com/user-attachments/files/17016216/e6decc58.json)

**Comment by fidelthomet** [comment]
this is very odd, when a template is initialised (a new story is created) the language is set based on the current language in settings.

https://github.com/fidelthomet/futuring-machines/blob/8d2624156a90c41a955378f09ccbf7ceae28cdb5/src/stores/commands.js#L391

Are you sure the language was set to english before creating the story?

Perhaps add the german translation to the template to see where we are at?

**Comment by jorditost** [comment]
this is super weird. 

This is the configuration in **Chrome**:

<img width="1179" alt="Screenshot 2024-09-17 at 11 34 04" src="https://github.com/user-attachments/assets/a970b049-72d8-462b-baa5-a9995f5c8f59">

Then, using the browser's console and typing this:

```window.navigator.language```

I get `en`:

<img width="227" alt="Screenshot 2024-09-17 at 11 44 55" src="https://github.com/user-attachments/assets/644d2284-7fe4-49ff-a8c6-188183bb6c3e">

Here the configuration in **Firefox** (I've even uninstalled the browser and installed it again using the English installation file, since I found out that some people have problems with the language when they used the installer from another language's page and then switched to English).

<img width="1381" alt="Screenshot 2024-09-17 at 11 48 58" src="https://github.com/user-attachments/assets/8bab201a-fea2-4dbd-a3cd-dc01585999b0">

Firefox's console says:
<img width="209" alt="Screenshot 2024-09-17 at 11 46 43" src="https://github.com/user-attachments/assets/497b9bf0-d798-40b7-b3d7-b2800ee6b346">

But then, when printing `lang.value`  in `commands.js` I get `de`:

<img width="203" alt="Screenshot 2024-09-17 at 11 48 11" src="https://github.com/user-attachments/assets/c9f14443-6f50-4594-a167-7ef74621b3fe">

I've added the German translation to the templates to be in both German and English. I've done a [pull request](https://github.com/fidelthomet/futuring-machines/pull/48).

**Comment by jorditost** [comment]
That was it 🥲 I hadn't understand that you had implemented a `/settings` page and thought you were talking about the `/settings`(also a subpage) from the browser.

**Comment by fidelthomet** [comment]
made a quick fix that the browser language (if available) is chosen initially
