### ISSUE TITLE
"Text selection +  append" (e.g. "elaborate") not working. LLM text should be appended at the end of the story.

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#46]
```
"trigger": "selection",
"mode": "append",
```

**Comment by fidelthomet** [comment]
can't reproduce. works fine for me with the `extrapolate` prompt

**Comment by jorditost** [comment]
I tried again and the selected text is not replaced. The LLM response is then added to the cursor position (which is the end of the selected text). The LLM response should be appended at the end of the story. Is the way it works at your end @fidelthomet?

**Comment by fidelthomet** [comment]
i don't get it, do you want to revert the changes from #28?

**Comment by fidelthomet** [comment]
but only for text selection?

**Comment by jorditost** [comment]
Yes, the behaviour from #28 (insert text at cursor position) should apply to the "continue" modes. 

The behaviour "text selection + append" was already implemented. This form of interacting with the text ("I want the story continuation specifically elaborate more aspect X that was already part of the story") came as a need from user tests and is also part of other tools / literature.

The "select + replace" modes should work as usual.

**Comment by jorditost** [comment]
I fixed it in:

https://github.com/fidelthomet/futuring-machines/commit/f928728bef8ca5be5e2cbb3a7dd7be3ed22e6a8a#diff-8511b2dfc6ae57b2892c6fe75924ea85b0767dcbb4b705e12323875ffdb49222R250

The commit should be part of the pull request.
