### ISSUE TITLE
Some parts marked as human but are AI generated (specially beginning of paragraphs)

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#9]
The text is sometimes not "classified" properly.

**Comment by fidelthomet** [comment]
could not reproduce this. can you check if this issue still persists in the latest version?

**Comment by jorditost** [comment]
That was after selecting "Continue writing":

<img width="1440" alt="Screenshot 2024-06-10 at 16 51 16" src="https://github.com/fidelthomet/futuring-machines/assets/859148/6e5fe452-2bae-48ca-942c-b9ff7563f407">

If you are using Ollama locally, try to use this API URL (the one I was using on the screenshot): https://futuringmachines.webis.de/api/generate

**Comment by fidelthomet** [comment]
This is very odd. I'm still struggling to reproduce the issue.

However, i ran into another issue where punctuation at the end of a paragraph was styled wrongly which i was able to resolve. Which might or might not be related.
<img width="335" alt="image" src="https://github.com/fidelthomet/futuring-machines/assets/1699985/c5269663-ac39-4366-8f03-3d873715e0cc">

Apart from this it could be a timing issue, but that doesn't seem very plausible to me either. But I tired to address this by setting the AI style before making the request.

If this still doesn't work I could potentially correct the style after everything is inserted.

Before I try that, can you try the latest version again? Also, is this happening frequently to you? I tried like 50 or so times without being able to reproduce
